# Generated by Django 5.1.15 on 2026-09-04 14:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="El teléfono solo puede contener números, espacios, guiones y un '+' opcional al inicio.", regex='^\\+?[\\d\\s-]+$')])),
                ('document', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El documento debe contener solo números.', regex='^\\d+$')])),
            ],
        ),
        migrations.CreateModel(
            name='PolicyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Vigente'), ('expired', 'Vencida'), ('renewed', 'Renovada')], default='active', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='policies.client')),
                ('policy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='policies.policytype')),
            ],
        ),
    ]
