# Generated by Django 5.1.15 on 2026-09-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
