# Generated by Django 5.1.15 on 2026-09-05 17:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_policy_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='renewed_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='policies.policy', verbose_name='Renovada desde'),
        ),
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El documento debe contener solo números.', regex='^\\d+$')], verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="El teléfono solo puede contener números, espacios, guiones y un '+' opcional al inicio.", regex='^\\+?[\\d\\s-]+$')], verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='policies.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='end_date',
            field=models.DateField(verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminada'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='number',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='policies.policytype', verbose_name='Tipo de Póliza'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='premium',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prima'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('active', 'Vigente'), ('expired', 'Vencida'), ('renewed', 'Renovada')], default='active', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='policytype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='policytype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
